// File generated by Antigravity based on google-services.json
// This allows Firebase to work on Windows and other platforms without full FlutterFire CLI setup.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFKZBT9-dbX5QWbqMBugPtvwolrzIikQY',
    appId: '1:48506804912:web:12df18981db9c93e87f975',
    messagingSenderId: '48506804912',
    projectId: 'rattel-5a4c6',
    authDomain: 'rattel-5a4c6.firebaseapp.com',
    storageBucket: 'rattel-5a4c6.firebasestorage.app',
    measurementId: 'G-T1VEK5WBN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1BeGO1JeemiB-DJGcZcfKCMATFW5Wudg',
    appId: '1:48506804912:android:0b7076505749227987f975',
    messagingSenderId: '48506804912',
    projectId: 'rattel-5a4c6',
    storageBucket: 'rattel-5a4c6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFKZBT9-dbX5QWbqMBugPtvwolrzIikQY',
    appId: '1:48506804912:web:12df18981db9c93e87f975',
    messagingSenderId: '48506804912',
    projectId: 'rattel-5a4c6',
    authDomain: 'rattel-5a4c6.firebaseapp.com',
    storageBucket: 'rattel-5a4c6.firebasestorage.app',
    measurementId: 'G-T1VEK5WBN4',
  );
}
